### ISSUE TITLE
Code signing (first iteration)

### ISSUE THREAD

**Issue by ruslan-bikkinin** [ruslan-bikkinin/code-push#1]
This is meta-issue to keep to-do list for code signing feature implementation.

What should be done in first place:

- [ ] CLI (`code-push` repo)
  - [x] Sync and adapt Richard's code base with latest changes from master in new branch `code-signing-new`
  - [ ] Update docs
     - [ ] Don't forget to mention, that Cordova-based apps signing is not supported yet
- [ ] Service (internal `service` repo)
  - [ ] Sync hash-utils from cli with service in new branch `code-signing-new`
- [ ] RN plugin (`react-native-code-push` repo)
  - [ ] Sync and adapt Richard's code base with latest changes from master in new branch `code-signing-new`
    - [ ] Add signature verification support on android
    - [ ] Add signature verification support on ios
  - [ ] Update docs

Afterwards actions (point by point):

- [ ] Update Service via PR
- [ ] Update CLI via PR
- [ ] Update RN plugin via PR
